// const a = {
//     "alias": "白秋-渋谷区",
//     "categories": Array [
//       Object {
//         "alias": "steak",
//         "title": "Steakhouses",
//       },
//       Object {
//         "alias": "teppanyaki",
//         "title": "Teppanyaki",
//       },
//     ],
//     "coordinates": Object {
//       "latitude": 35.6562822526991,
//       "longitude": 139.700982063529,
//     },
//     "display_phone": "+81 3-3461-0546",
//     "distance": 3963.949707488834,
//     "id": "zdA3W7oWPbF4LsNfD35yIw",
//     "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/jzfK_9cllPfijGJG2d3Gew/o.jpg",
//     "is_closed": false,
//     "location": Object {
//       "address1": "桜丘町17-10",
//       "address2": "MCD Building 1F",
//       "address3": null,
//       "city": "Shibuya",
//       "country": "JP",
//       "display_address": Array [
//         "桜丘町17-10",
//         "MCD Building 1F",
//         "Shibuya, 東京都 〒150-0031",
//         "Japan",
//       ],
//       "state": "13",
//       "zip_code": "150-0031",
//     },
//     "name": "Hakushu",
//     "phone": "+81334610546",
//     "price": "￥￥￥",
//     "rating": 5,
//     "review_count": 101,
//     "transactions": Array [],
//     "url": "https://www.yelp.com/biz/%E7%99%BD%E7%A7%8B-%E6%B8%8B%E8%B0%B7%E5%8C%BA?adjust_creative=nYWytkv5DFn2BTQsPFnqxw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=nYWytkv5DFn2BTQsPFnqxw",
//   },